
###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nemo
$menu = wofi --show drun


#################
### AUTOSTART ###
#################

# SOLO cosas de Hyprland (nada de Plasma)
exec-once = hyprpaper
exec-once = waybar
exec-once = swaync
exec-once = hypridle
exec-once = hyprsunset
exec-once = wl-paste --watch cliphist store


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Evita que apps crean que estás en KDE
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland


#############
### INPUT ###
#############

input {
    kb_layout = es
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

##############################
### SOURCE OTHER FILES ###
##############################

source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
